//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.DAL.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class tmpmEntities2 : DbContext
    {
        public tmpmEntities2()
            : base("name=tmpmEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tm_pm_userinfo> tm_pm_userinfo { get; set; }
        public DbSet<xy_sp_chapter> xy_sp_chapter { get; set; }
        public DbSet<xy_sp_equipment> xy_sp_equipment { get; set; }
        public DbSet<xy_sp_map> xy_sp_map { get; set; }
        public DbSet<xy_sp_outfit> xy_sp_outfit { get; set; }
        public DbSet<xy_sp_outfitequipment> xy_sp_outfitequipment { get; set; }
        public DbSet<xy_sp_skill> xy_sp_skill { get; set; }
        public DbSet<xy_sp_spirit> xy_sp_spirit { get; set; }
        public DbSet<xy_sp_spiritequipment> xy_sp_spiritequipment { get; set; }
        public DbSet<xy_sp_spiritskill> xy_sp_spiritskill { get; set; }
        public DbSet<xy_sp_task> xy_sp_task { get; set; }
        public DbSet<xy_sp_taskoption> xy_sp_taskoption { get; set; }
        public DbSet<xy_sp_taskspirit> xy_sp_taskspirit { get; set; }
        public DbSet<xy_sp_userinfo> xy_sp_userinfo { get; set; }
        public DbSet<xy_sp_userspirit> xy_sp_userspirit { get; set; }
        public DbSet<xy_sp_userspiritpackage> xy_sp_userspiritpackage { get; set; }
    }
}
