//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tm_pm_userinfo
    {
        public string USERID { get; set; }
        public string LOGINNAME { get; set; }
        public string LOGINPWD { get; set; }
        public string MOBILEPHONE { get; set; }
        public string EMAIL { get; set; }
        public string CREATEUSERID { get; set; }
        public Nullable<System.DateTime> CREATEDATETIME { get; set; }
        public string EDITUSERID { get; set; }
        public Nullable<System.DateTime> EDITDATETIME { get; set; }
        public string OWNERID { get; set; }
        public bool ISDELETED { get; set; }
        public string CREATEUSERNAME { get; set; }
        public string EDITUSERNAME { get; set; }
        public string OWNERNAME { get; set; }
        public Nullable<int> USERTYPE { get; set; }
    }
}
