//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class xy_sp_task
    {
        public string chapterID { get; set; }
        public string TaskID { get; set; }
        public string TaskName { get; set; }
        public string TaskDescript { get; set; }
        public string NpcName { get; set; }
        public Nullable<decimal> IsBattleTask { get; set; }
    }
}
