//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class xy_sp_skill
    {
        public string SkillID { get; set; }
        public string SkillName { get; set; }
        public string SkillDescription { get; set; }
        public string SkillPathPrompt { get; set; }
        public string SkillType { get; set; }
        public Nullable<decimal> SkillGainValue { get; set; }
        public string ExpendType { get; set; }
        public Nullable<decimal> ExpendValue { get; set; }
        public Nullable<decimal> isGroupinjury { get; set; }
        public Nullable<decimal> injuryCount { get; set; }
        public Nullable<decimal> NeedLevel { get; set; }
    }
}
