//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class xy_sp_spirit
    {
        public string SpiritID { get; set; }
        public string SpiritName { get; set; }
        public Nullable<decimal> SpiritLife { get; set; }
        public Nullable<decimal> SpiritMagic { get; set; }
        public Nullable<decimal> PhysicalResistance { get; set; }
        public Nullable<decimal> MagicResistance { get; set; }
        public Nullable<decimal> SpiritLevel { get; set; }
        public Nullable<decimal> SpiritExperience { get; set; }
        public Nullable<decimal> SpiritMoney { get; set; }
        public Nullable<decimal> PhysicalHarm { get; set; }
        public Nullable<decimal> MagicHarm { get; set; }
        public Nullable<decimal> Spiritspeed { get; set; }
    }
}
