//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class xy_sp_map
    {
        public string AddrID { get; set; }
        public string AddrName { get; set; }
        public string AddrDescript { get; set; }
        public Nullable<decimal> AddrX { get; set; }
        public Nullable<decimal> AddrY { get; set; }
        public string FatherAddrID { get; set; }
    }
}
